### ISSUE TITLE
Переехать с pickle на SQL

### ISSUE THREAD

**Issue by evgfilim1** [evgfilim1/spin_everyday_bot#16]

**Comment by OctoNezd** [comment]
можешь взять `dataset`

а можешь и не брать, мне насрать

**Comment by evgfilim1** [comment]
@OctoNezd можно взять `peewee`, тоже годная вещь

**Comment by mostm** [comment]
Алхимию? `sqlalchemy`

**Comment by evgfilim1** [comment]
@mostm Вариантов много, на самом деле. Надо смотреть по скорости (чтоб критических потерь не было) и удобству.

**Comment by evgfilim1** [comment]
Реализовано в 72b1cb94cf6f43f12bc3212ef558ef278027eb6e
