### ISSUE TITLE
Нет ответа на /settings в ЛС

### ISSUE THREAD

**Issue by evgfilim1** [evgfilim1/spin_everyday_bot#20]
Проблема состоит в том, что идёт проверка администраторов чата, а в ЛС их нет, следовательно, бот не отвечает, выдавая ошибку.

**Comment by HexwellC** [comment]
Можно проверять чаты на наличие в них человека, а там уже проверять есть ли у него права администратора. Затем составлять интерфейс с выбором, настройки какого чата хочет изменить пользователь.
Отдалённо что-то похожее делает GitHub бот.

**Comment by evgfilim1** [comment]
@HexwellC Идея хорошая, но в данном случае речь идёт о настройках конкретного пользователя. Раньше возможно было вызвать только настройки чата и только из самого чата, затем я усовершенствовал функцию, добавив возможность вызова личных настроек в ЛС, но забыл убрать проверку на администратора.
