### ISSUE TITLE
На пустой /setsn показывать текущее название розыгрыша

### ISSUE THREAD

**Issue by evgfilim1** [evgfilim1/spin_everyday_bot#6]

**Comment by fumycat** [comment]
@evgfilim1 🐛 New issue spin_everyday_bot#6 На пустой /setsn показывать текущее название розыгрыша (https://github.com/evgfilim1/spin_everyday_bot/issues/6)
by @evgfilim1 (https://github.com/evgfilim1)



Reply to this message to post a comment on GitHub.

**Comment by evgfilim1** [comment]
Fixed
